user/src/main/java/com/coopang/user/UserApplication.java
user/src/main/java/com/coopang/user/application/response/LoginResponseDto.java
user/src/main/java/com/coopang/user/application/response/UserResponseDto.java
user/src/main/java/com/coopang/user/application/service/AuthService.java
user/src/main/java/com/coopang/user/application/service/RedisService.java
user/src/main/java/com/coopang/user/application/service/UserService.java
user/src/main/java/com/coopang/user/domain/entity/base/BaseEntity.java
user/src/main/java/com/coopang/user/domain/entity/base/BaseTimeEntity.java
user/src/main/java/com/coopang/user/domain/entity/user/UserEntity.java
user/src/main/java/com/coopang/user/domain/repository/UserRepository.java
user/src/main/java/com/coopang/user/domain/service/UserDomainService.java
user/src/main/java/com/coopang/user/infrastructure/jwt/JwtUtil.java
user/src/main/java/com/coopang/user/infrastructure/redis/RedisConfig.java
user/src/main/java/com/coopang/user/infrastructure/repository/UserJpaRepository.java
user/src/main/java/com/coopang/user/infrastructure/repository/UserRepositoryCustom.java
user/src/main/java/com/coopang/user/infrastructure/repository/UserRepositoryCustomImpl.java
user/src/main/java/com/coopang/user/infrastructure/repository/UserRepositoryImpl.java
user/src/main/java/com/coopang/user/infrastructure/swagger/SwaggerConfig.java
user/src/main/java/com/coopang/user/presentation/controller/AuthController.java
user/src/main/java/com/coopang/user/presentation/controller/UserController.java
user/src/main/java/com/coopang/user/presentation/request/ChangePasswordRequestDto.java
user/src/main/java/com/coopang/user/presentation/request/LoginRequestDto.java
user/src/main/java/com/coopang/user/presentation/request/SearchRequestDto.java
user/src/main/java/com/coopang/user/presentation/request/SignupRequestDto.java
user/src/main/java/com/coopang/user/presentation/request/UpdateRequestDto.java
user/src/main/java/com/coopang/user/presentation/request/UserSearchCondition.java
user/src/test/java/com/coopang/user/QuerydslBasicTest.java
user/src/test/java/com/coopang/user/UserApplicationTests.java
user/src/test/java/com/coopang/user/UserJpaRepositoryTest.java

[Update] Adjust queryDSL & DDD Layered Architecture, [Add] SwaggerConfig

[Update] Adjust queryDSL & DDD Layered Architecture, [Add] SwaggerConfig

---

user/src/main/java/com/coopang/user/UserApplication.java
user/src/main/java/com/coopang/user/application/service/AuthService.java
user/src/main/java/com/coopang/user/application/service/UserService.java
user/src/main/java/com/coopang/user/infrastructure/cache/CacheConfig.java
user/src/main/java/com/coopang/user/presentation/controller/AuthController.java

[Add] user server: add cache
Add spring-boot-starter-cache, caffeine
Adjust @EnableCaching, @Cacheable, @CacheEvict

[Add] user server: add cache

---

build.gradle
docker-compose.yml
eureka/build.gradle
gateway/build.gradle
user/build.gradle

[Style] update gradle: code convention 4space
Add user server gradle: QueryDSL, redis, cache
[Update] docker-compose.yml
Add prometheus, grafana, loki for monitoring
Add eureka, gateway, user, hub
Add init.sql for sql script mount
[Style] Update code convension 4 spaces

#20 init hub server

---

user/build.gradle
user/src/main/java/com/coopang/user/UserApplication.java
user/src/main/java/com/coopang/user/application/request/UserDto.java
user/src/main/java/com/coopang/user/application/service/AuthService.java
user/src/main/java/com/coopang/user/application/service/UserService.java
user/src/main/java/com/coopang/user/domain/entity/user/UserEntity.java
user/src/main/java/com/coopang/user/domain/repository/UserRepository.java
user/src/main/java/com/coopang/user/domain/service/UserDomainService.java
user/src/main/java/com/coopang/user/infrastructure/repository/Querydsl4RepositorySupport.java
user/src/main/java/com/coopang/user/infrastructure/repository/UserRepositoryCustomImpl.java
user/src/main/java/com/coopang/user/presentation/controller/AuthController.java
user/src/main/java/com/coopang/user/presentation/controller/UserController.java
user/src/main/java/com/coopang/user/presentation/request/UserSearchCondition.java
user/src/test/java/com/coopang/user/QuerydslBasicTest.java
user/src/test/java/com/coopang/user/UserApplicationTests.java

[Add&Update] user server : Mapper, openfeign, UserRepositoryCustomImpl
[Add] user server
1. Add gradle Mapper, openfeign
2. Add UserDto.class for DDD presentation's DTO seperated from Service layered DTO
3. Add Querydsl4RepositorySupport
[Update] user server
1. Delete SearchRequestDto
2. Add Pageable parameter to searchUsers function, getAllUsers function
3. Update UserDomainService about deleting updateUser, blockUser, deleteUser
4. Update UserRepositoryCustomImpl for adjust Querydsl4RepositorySupport
5. Update AuthController for no using presentation's DTO in authService

[Add&Update] user server : Mapper, openfeign, UserRepositoryCustomImpl

---

INFRA/api-config/src/main/java/com/coopang/apiconfig/security/config/SecurityFilterProperties.java

* Related - #54 
[Update] SecurityFilterProperties : 개선
- Component 제거
- setter 제거
- https://cutewonny.tistory.com/entry/Component-Configuration 에 설명
- 10/4 금요일 오전에 리뷰 드렸어요

[Update] SecurityFilterProperties : 개선

---

DATA/api-data/src/main/java/com/coopang/apidata/application/delivery/enums/DeliveryStatusEnum.java
DATA/api-data/src/main/java/com/coopang/apidata/application/user/UserPermissionValidator.java
DATA/api-data/src/main/java/com/coopang/apidata/application/user/enums/UserRoleEnum.java
DATA/api-data/src/main/java/com/coopang/apidata/application/user/response/UserResponse.java
DATA/api-data/src/main/java/com/coopang/apidata/jpa/entity/base/BaseEntity.java
INFRA/api-config/src/main/java/com/coopang/apiconfig/security/config/SecurityFilterProperties.java

* Related - #59  
* Related - #43 
- 민철님 작업 : DeliveryStatusEnum
- 정원님 작업 : UserRoleEnum, UserPermissionValidator, UserResponse, BaseEntity
- 다른 DEV-서버별 브랜치에서 DEV-branch pull 받아서 공통되는 거 쓰시면 되요

#43 dev apidata

---

INFRA/api-config/src/main/java/com/coopang/apiconfig/error/GlobalExceptionHandler.java
INFRA/api-config/src/main/java/com/coopang/apiconfig/security/filter/CommonApiHeaderFilter.java

* Related - #65 
* [Update] api-cofig app
- [Update] GlobalExceptionHandler : Add @Slf4j, Change errorMessage containing all error messages
- [Update] CommonApiHeaderFilter : userId, role 체크를 먼저하도록 함
*  각자 서버 pull -> 하위에 속한 피쳐에서 필요하면 각자 서버에서 하위에 속한 피쳐로 pull

[Update] api-cofig app

---

BOOT/order/src/main/java/com/coopang/order/application/CancelDelivery.java
BOOT/order/src/main/java/com/coopang/order/application/ErrorCancelOrder.java
BOOT/order/src/main/java/com/coopang/order/application/RollbackProduct.java
BOOT/order/src/main/java/com/coopang/order/application/service/OrderService.java
BOOT/order/src/main/java/com/coopang/order/application/service/PaymentService.java
BOOT/order/src/main/java/com/coopang/order/domain/entity/payment/PaymentEntity.java
BOOT/order/src/main/java/com/coopang/order/domain/repository/PaymentRepository.java
BOOT/order/src/main/java/com/coopang/order/presentation/controller/PGController.java

* Related - #87 
* 임의의 PG사 API url 수정 (payments/v1/pg, payments/v1/pg/cancel)
* 주문 취소후 결제 취소에 관한 부분 구현

[update] payment쪽 kafka 송수신 작업 완료 & PG사 결제 취소 요청 생성 및 url 수정

---

DATA/api-data/src/main/java/com/coopang/apidata/application/order/enums/OrderStatusEnum.java
DATA/api-data/src/main/java/com/coopang/apidata/application/payment/enums/PaymentMethodEnum.java
DATA/api-data/src/main/java/com/coopang/apidata/application/payment/enums/PaymentStatusEnum.java

* Related - #91 
* OrderStatusEnum 추가
* PaymentMethodEnum 추가
* PaymentStatusEnum 추가

[update] order / payment Enum 등록

---

BOOT/product/src/main/java/com/coopang/product/application/kafka/ProductConsumer.java
BOOT/product/src/main/java/com/coopang/product/infrastructure/configuration/ConsumerApplicationKafkaConfig.java

- Related - #83 
consumer 폴더위치 변경 및 rollback 시 메소드 변경

[Update] consumer 폴더위치 변경 및 rollback 함수 정정 #83

---

BOOT/delivery/src/main/java/com/coopang/delivery/application/service/DeliveryService.java
BOOT/delivery/src/main/java/com/coopang/delivery/domain/service/DeliveryDomainService.java
BOOT/delivery/src/main/java/com/coopang/delivery/infrastructure/config/ConsumerApplicationKafkaConfig.java
BOOT/delivery/src/main/java/com/coopang/delivery/infrastructure/config/ProducerApplicationKafkaConfig.java
BOOT/order/src/main/java/com/coopang/order/application/request/PaymentDto.java
BOOT/order/src/main/java/com/coopang/order/application/response/OrderCancelResponseDto.java
BOOT/order/src/main/java/com/coopang/order/application/response/OrderResponseDto.java
BOOT/order/src/main/java/com/coopang/order/application/response/PaymentResponseDto.java

* Related - #100 
* complete_delivery 수신 및 구현 완료
* cancel_delivery 수신 및 구현 완료

[update] delivery kafka 작업 완료

---

BOOT/delivery/src/main/java/com/coopang/delivery/application/service/DeliveryService.java
BOOT/order/src/main/java/com/coopang/order/application/service/OrderService.java
BOOT/order/src/main/java/com/coopang/order/application/service/PaymentService.java

* Related - #100 
* 사용하지 않은 import때문에 Order쪽 Application이 실행 되지 않아 수정 후 정상작동 확인

[fix] 잘못된 import인한 오류 수정

---

INFRA/api-communication/src/main/java/com/coopang/apicommunication/kafka/message/CompleteProduct.java
INFRA/api-communication/src/main/java/com/coopang/apicommunication/kafka/message/LowStockNotification.java

* Related - #108 
* 결제 정보에 맞춰 메시징 변경
* 슬랙알림 메시지 추가
* 

[Update] kafka message add and update

---

DATA/api-data/src/main/java/com/coopang/apidata/application/hub/enums/ShipperTypeEnum.java
DATA/api-data/src/main/java/com/coopang/apidata/application/user/enums/UserRoleEnum.java
DATA/api-data/src/main/java/com/coopang/apidata/application/user/response/UserResponse.java

* Related - #57 
[Update] Hub, Shipper, Company, User CRUD 생성, 수정에 관련
- [Add] ShipperTypeEnum : 배송기사 타입 enum 추가
- [Update] UserRoleEnum : Authority가 아닌 UserRoleEnum 기준으로 비교, 찾기 수정
- [Update] UserResponse : Address 필드 추가
* 

[Update] Hub, Shipper, Company, User CRUD 생성, 수정에 관련

---

INFRA/api-config/src/main/java/com/coopang/apiconfig/feignClient/FeignConfig.java
INFRA/api-config/src/main/java/com/coopang/apiconfig/mapper/ModelMapperConfig.java

* Related - #57 
* [Update] hub-app 에 맞게 수정
- [Update] ModelMapperConfig : ModelMapper 객체 생성 추가
- [Update] FeignConfig : todo 추가
* 

[Update] hub-app 에 맞게 수정

---

BOOT/product/src/main/java/com/coopang/product/application/kafka/ProductConsumer.java
BOOT/product/src/main/java/com/coopang/product/application/service/product/ProductService.java
BOOT/product/src/main/java/com/coopang/product/domain/entity/productStock/ProductStockEntity.java
BOOT/product/src/main/java/com/coopang/product/infrastructure/configuration/ConsumerApplicationKafkaConfig.java

* Related - #102 
* 메시징 변경으로 인해 orderTotalPrice 추가
* 카프카 에러 시 DLT로 보내는 로직 추가 (추후 다른 에러처리 방안 모색)
* 

[Update] kafka 연결 테스트 중 수정 사항 구현

---

BOOT/hub/src/main/java/com/coopang/hub/infrastructure/configuration/CompanyDataInitializer.java
BOOT/hub/src/main/java/com/coopang/hub/infrastructure/configuration/ShipperDataInitializer.java
BOOT/hub/src/main/java/com/coopang/hub/presentation/controller/company/CompanyClientControllerImpl.java
BOOT/hub/src/main/java/com/coopang/hub/presentation/controller/company/CompanyController.java
BOOT/hub/src/main/java/com/coopang/hub/presentation/controller/hub/HubClientControllerImpl.java
BOOT/hub/src/main/java/com/coopang/hub/presentation/controller/hub/HubController.java
BOOT/hub/src/main/java/com/coopang/hub/presentation/controller/shipper/ShipperClientControllerImpl.java
BOOT/hub/src/main/java/com/coopang/hub/presentation/controller/shipper/ShipperController.java
BOOT/hub/src/main/java/com/coopang/hub/presentation/controller/user/UserClientControllerImpl.java
BOOT/user/src/main/java/com/coopang/user/infrastructure/configuration/UserDataInitializer.java
BOOT/user/src/main/java/com/coopang/user/presentation/controller/UserController.java
BOOT/user/src/main/java/com/coopang/user/presentation/request/UserSearchConditionRequestDto.java
DATA/api-data/src/main/java/com/coopang/apidata/application/user/enums/UserRoleEnum.java
DATA/api-data/src/main/java/com/coopang/apidata/application/user/request/UserSearchConditionRequest.java
INFRA/api-communication/src/main/java/com/coopang/apicommunication/ApiCommunicationApplication.java
INFRA/api-communication/src/main/java/com/coopang/apicommunication/feignClient/user/UserClient.java
INFRA/api-communication/src/main/java/com/coopang/apicommunication/feignclient/company/CompanyClient.java
INFRA/api-communication/src/main/java/com/coopang/apicommunication/feignclient/company/CompanyClientController.java
INFRA/api-communication/src/main/java/com/coopang/apicommunication/feignclient/company/CompanyClientService.java
INFRA/api-communication/src/main/java/com/coopang/apicommunication/feignclient/hub/HubClient.java
INFRA/api-communication/src/main/java/com/coopang/apicommunication/feignclient/hub/HubClientController.java
INFRA/api-communication/src/main/java/com/coopang/apicommunication/feignclient/hub/HubClientService.java
INFRA/api-communication/src/main/java/com/coopang/apicommunication/feignclient/shipper/ShipperClient.java
INFRA/api-communication/src/main/java/com/coopang/apicommunication/feignclient/shipper/ShipperClientController.java
INFRA/api-communication/src/main/java/com/coopang/apicommunication/feignclient/shipper/ShipperClientService.java
INFRA/api-communication/src/main/java/com/coopang/apicommunication/feignclient/user/UserClientController.java
INFRA/api-config/src/main/java/com/coopang/apiconfig/feignClient/FeignConfig.java

* Related - #130
- [Update] CompanyController, HubController, ShipperController
- [Update] UserController : 서버권한 추가, [@Valid](https://github.com/Valid) UserSearchConditionRequestDto 적용
- [Update] UserSearchConditionRequestDto : [@Email](https://github.com/Email) 적용
- [Update] UserSearchConditionRequest : [@Email](https://github.com/Email) 추가
- [Update] **ClientController : public 추가
- [Update] **ClientService : [@PathVariable](https://github.com/PathVariable) 제거
- [Update] UserClient : [@Valid](https://github.com/Valid) 추가 [@Email](https://github.com/Email)
- [Update] Company 유저 아이디 일치하게 수정
- [Update] Company 유저 아이디 일치하게 수정
- [Update] HubMapInitializer 제거, hubMap.put 변경
- [Update] ApiCommunicationApplication : [@EnableFeignClients](https://github.com/EnableFeignClients), …

#130 dev apidata feature server role

---

INFRA/api-communication/build.gradle
INFRA/api-communication/src/main/java/com/coopang/apicommunication/kafka/consumer/MessageConsumer.java
INFRA/api-communication/src/main/java/com/coopang/apicommunication/kafka/consumer/MessageService.java
INFRA/api-communication/src/main/java/com/coopang/apicommunication/kafka/message/CancelPayment.java
INFRA/api-communication/src/main/java/com/coopang/apicommunication/kafka/message/ProcessChangeStatus.java
INFRA/api-communication/src/main/java/com/coopang/apicommunication/kafka/producer/KafkaMessageProducerService.java
INFRA/api-communication/src/main/java/com/coopang/apicommunication/kafka/producer/MessageProducer.java

* Related - #84 
* kafka/consumer/MessageConsumer.java
* kafka/consumer/MessageService.java
* kafka/producer/KafkaMessageProducerService.java
* kafka/producer/MessageProducer.java

[update] message 작업 및 공통모듈 작업 진행

---

DATA/api-data/src/main/java/com/coopang/apidata/application/order/response/OrderResponse.java

[update] feignclient를 위한 OrderResponse 추가

---

INFRA/api-communication/src/main/java/com/coopang/apicommunication/feignClient/order/OrderClient.java
INFRA/api-communication/src/main/java/com/coopang/apicommunication/feignClient/order/OrderClientController.java
INFRA/api-communication/src/main/java/com/coopang/apicommunication/feignClient/order/OrderClientService.java

* Related - #147 
* OrderClient 추가
* OrderClientController 추가
* OrderClientService 추가
* 조건 (주문 상태 및 삭제)는 Order_Server 내에서 진행 할 예정

[update] feignclient를 위한 order쪽 개발

---

INFRA/api-communication/src/main/java/com/coopang/apicommunication/kafka/message/LowStockNotification.java

* Related - #152 
* UUID managerId -> String slackId로 변경
* 

[Update] 재고부족알림관련 메시지 변경

---

DATA/core-data/src/main/java/com/coopang/coredata/user/constants/HeaderConstants.java
INFRA/api-config/src/main/java/com/coopang/apiconfig/feignClient/FeignConfig.java
INFRA/api-config/src/main/java/com/coopang/apiconfig/security/UserMetadata.java
INFRA/api-config/src/main/java/com/coopang/apiconfig/security/filter/CommonApiHeaderFilter.java

* Related - #143 
- [Update] FeignConfig : SERVER_USER_ID 추가, "SERVER" -> UserRoleEnum.SERVER 변경
- [Update] CommonApiHeaderFilter : userEmail, token 추가, ROLE_PREFIX 정리
- [Add] UserMetadata : userEmail, token 추가 정보 클래스 생성
- [Update] HeaderConstants : Add SERVER_USER_ID, ROLE_PREFIX

#45 dev apiconfig

---

BOOT/product/src/main/java/com/coopang/product/application/request/category/CategoryDto.java
BOOT/product/src/main/java/com/coopang/product/application/response/category/CategoryResponseDto.java
BOOT/product/src/main/java/com/coopang/product/application/service/category/CategoryService.java
BOOT/product/src/main/java/com/coopang/product/domain/entity/category/CategoryEntity.java
BOOT/product/src/main/java/com/coopang/product/domain/repository/category/CategoryRepository.java
BOOT/product/src/main/java/com/coopang/product/domain/service/category/CategoryDomainService.java
BOOT/product/src/main/java/com/coopang/product/infrastructure/configuration/ProductDataInitializer.java
BOOT/product/src/main/java/com/coopang/product/infrastructure/repository/product/ProductRepositoryCustomImpl.java
BOOT/product/src/main/java/com/coopang/product/presentation/controller/category/CategoryController.java
BOOT/product/src/main/java/com/coopang/product/presentation/controller/product/ProductController.java
BOOT/product/src/main/java/com/coopang/product/presentation/request/category/CreateCategoryRequestDto.java
BOOT/product/src/main/java/com/coopang/product/presentation/request/category/UpdateCategoryRequestDto.java

* Related - #161 
- 카테고리 CRUD 추가
* 시드데이터 yml으로 설정할수있도록 수정
* 시드데이터 상품 100개로 변경
* search 시 post맵핑으로 request body가 없을 경우 에러발생하는 문제 해결
* search 시 maxPrice가 없을 경우 0.0으로 설정되어 전체상품이 안나오는 문제 해결
* 

[상품] 배포 후 변경사항들 수정

---

BOOT/product/src/main/java/com/coopang/product/application/request/product/ProductBaseSearchConditionDto.java
BOOT/product/src/main/java/com/coopang/product/application/request/product/ProductSearchConditionDto.java
BOOT/product/src/main/java/com/coopang/product/application/service/product/ProductService.java
BOOT/product/src/main/java/com/coopang/product/domain/repository/product/ProductRepository.java
BOOT/product/src/main/java/com/coopang/product/infrastructure/repository/product/ProductRepositoryCustom.java
BOOT/product/src/main/java/com/coopang/product/infrastructure/repository/product/ProductRepositoryCustomImpl.java
BOOT/product/src/main/java/com/coopang/product/presentation/controller/product/ProductController.java
BOOT/product/src/main/java/com/coopang/product/presentation/request/product/ProductBaseSearchConditionRequestDto.java
BOOT/product/src/main/java/com/coopang/product/presentation/request/product/ProductSearchConditionRequestDto.java

* Related - #164 
* [Refactor] RequestBody가 없는 경우 empty(기본생성자로 생성되도록) 변경
*  [Refactor] change SearchConditionDto -> SearchConditionRequestDto
* [Refactor] add 주석
*  [Update] search 필터링 조건에 productId,companyId 추가
* 캐싱 이름 및 캐싱 key 변경
* 

[Refactor] refactor the search method

---

BOOT/product/src/main/java/com/coopang/product/application/request/product/ProductSearchConditionDto.java
BOOT/product/src/main/java/com/coopang/product/presentation/controller/product/ProductController.java

* Related - #164 
* toString,hashcode, equals 자동으로 생성
* 코드 깔끔하도록 변경
* 

[Refactor] refactor the code

---

BOOT/product/src/main/java/com/coopang/product/application/service/product/ProductService.java
BOOT/product/src/main/java/com/coopang/product/infrastructure/configuration/ConsumerApplicationKafkaConfig.java
BOOT/product/src/main/java/com/coopang/product/infrastructure/configuration/ProducerApplicationKafkaConfig.java
BOOT/product/src/main/java/com/coopang/product/infrastructure/configuration/ProductDataInitializer.java
BOOT/product/src/main/resources/application.yml

* Related - #175 
* [Fix] fix the cache error in ProductService
* [Update] 하드코딩된 부분 yml로 설정
* [Update] 시드데이터 소숫점 부분 삭제
* 

[Fix] fix the cache error

---

BOOT/product/src/main/java/com/coopang/product/application/request/product/ProductBaseSearchConditionDto.java
BOOT/product/src/main/java/com/coopang/product/application/service/product/ProductService.java

* Related - #175 
* [Update] getAllProductInCompany , getAllProductInCompany 의 cache key 변경 
* [Update] ProductBaseSearchConditionDto 내 toString, hashCode, equals 추가
* 

[Update] update cache key

---

BOOT/product/src/main/resources/application.yml

* Related - #175 
* [Update] set the environment value in application.yml
* [Update] delete redis in application.yml
* 

[Update] dev product update application.yml
